spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: mysecretkey
      expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: INFO
    com.ecommerce: DEBUG
