spring:
  config:
    activate:
      on-profile: dev

# Data source configuration using a file-based H2 database

  datasource:
    url: jdbc:h2:file:./data/proddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

# Enable H2 console for development

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082
