spring:
  application:
    name: user-service
  profiles:
    active: dev
#  config:
#    import: optional:configserver:http://localhost:8888  # Imports configuration from the Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
